# Generated by Django 4.2 on 2023-04-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления')),
                ('description', models.TextField(verbose_name='описание')),
                ('demo', models.BooleanField(default=False, verbose_name='демо-версия')),
                ('owner_id', models.IntegerField(verbose_name='id владельца')),
                ('owner_name', models.CharField(max_length=255, verbose_name='имя владельца')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
    ]
